spring:
  application:
    name: weather-city

eureka:
  client:
    service-url:
      defaultZone: http://gniu-pro:8761/eureka/
  instance:
    hostname: gniu-pro
    prefer-ip-address: true
server:
  port: 8001