eureka:
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false
  instance:
    hostname: gniu-pro
    prefer-ip-address: true
spring:
  application:
    name: eureka
server:
  port: 8761